# Generated by Django 5.2.13 on 2026-04-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tour_available_dates_tour_max_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
